name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt update
        # Install Flatpak runtime with newer GTK
        sudo apt install -y flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.gnome.Platform//46
        
        # Install base dependencies
        sudo apt install -y \
          libdbus-1-dev \
          pkg-config \
          libsqlite3-dev \
          protobuf-compiler \
          libcairo2-dev \
          libpango1.0-dev \
          libgdk-pixbuf2.0-dev \
          libglib2.0-dev \
          build-essential
        
        # Use Flatpak GTK4
        export PKG_CONFIG_PATH="/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/46/active/files/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
    
    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
    
    - name: Debug GTK version
      run: |
        pkg-config --modversion gtk4 || echo "GTK4 not found"
        find /usr -name "gtk4.pc" 2>/dev/null || echo "No gtk4.pc found"
        ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/ | grep gtk
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
